trigger:
- Azure

variables:
  projectName: 'Winnocare'

stages:
  - stage: Build
    displayName: Build Ionic - Android projects
    jobs:
      # Debug build
      - job: Build_Ionic_Android_Debug
        variables:
          - name: buildConfiguration
            value: debug
        displayName: Build Debug
        pool:
            name: default
            demands:
            - agent.name -equals Ridhams-MacBook-Air
        steps:   
          - script: npm install -g @ionic/cli
            displayName: 'Install Ionic CLI'

          - task: Npm@1
            inputs:
              workingDir: '$(Build.SourcesDirectory)/$(projectName)'
              command: install
            displayName: 'NPM Install'

          - powershell: |
              ionic cap build android --no-open
              npx cap sync android
              cd android
              ./gradlew assemble$(buildConfiguration)
            workingDirectory: $(Build.SourcesDirectory)/$(projectName)
            displayName: 'Build Android Project'

          - task: Gradle@2
            displayName: 'Building Android App'
            inputs:
              #workingDirectory: $(Build.SourcesDirectory)/$(projectName)
              gradleWrapperFile: $(Build.SourcesDirectory)/$(projectName)/android/gradlew
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              testResultsFiles: '**/TEST-*.xml'
              tasks: assemble$(buildConfiguration)
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(projectName)"
              ArtifactName: "$(projectName)"
              publishLocation: "Container"
            displayName: "Publish artifacts"

      # Release build